version: '3.8'

services:
  go4it-backend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    command: npm run dev

  go4it-frontend:
    volumes:
      - ./frontend:/app
    command: npm start
