version: '3.8'

services:
  go4it-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=test
      - MONGO_URI=mongodb://mongo:27017/go4it_test
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    command: npm test

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
