#!/bin/bash

echo "🔧 OAuth Configuration Helper for AthleteAI"
echo "==========================================="
echo ""
echo "This script will help you configure OAuth for AthleteAI."
echo "You'll need to manually create applications on each platform:"
echo ""
echo "1. 🌐 Google OAuth Setup:"
echo "   📍 Go to: https://console.cloud.google.com/"
echo "   ✅ Create/select a project"
echo "   ✅ Enable Google+ API"
echo "   ✅ Go to 'Credentials' → 'Create Credentials' → 'OAuth 2.0 Client IDs'"
echo "   ✅ Configure OAuth consent screen"
echo "   ✅ Set application type to 'Web application'"
echo "   ✅ Add redirect URI: http://localhost:5000/api/v1/auth/google/callback"
echo "   📋 Copy Client ID and Client Secret"
echo ""
echo "2. 🐙 GitHub OAuth Setup:"
echo "   📍 Go to: https://github.com/settings/developers"
echo "   ✅ Click 'OAuth Apps' → 'New OAuth App'"
echo "   ✅ Fill application details:"
echo "      - Application name: AthleteAI"
echo "      - Homepage URL: http://localhost:3000"
echo "      - Authorization callback URL: http://localhost:5000/api/v1/auth/github/callback"
echo "   📋 Copy Client ID and Client Secret"
echo ""
echo "3. 📘 Facebook OAuth Setup:"
echo "   📍 Go to: https://developers.facebook.com/"
echo "   ✅ Create a new app or select existing"
echo "   ✅ Add 'Facebook Login' product"
echo "   ✅ Go to Facebook Login → Settings"
echo "   ✅ Add redirect URI: http://localhost:5000/api/v1/auth/facebook/callback"
echo "   📋 Copy App ID and App Secret"
echo ""
echo "📝 After creating the apps, update backend/.env with your credentials:"
echo "   GOOGLE_CLIENT_ID=your_google_client_id"
echo "   GOOGLE_CLIENT_SECRET=your_google_client_secret"
echo "   GITHUB_CLIENT_ID=your_github_client_id"
echo "   GITHUB_CLIENT_SECRET=your_github_client_secret"
echo "   FACEBOOK_APP_ID=your_facebook_app_id"
echo "   FACEBOOK_APP_SECRET=your_facebook_app_secret"
echo ""
echo "🚀 Then run: ./start_dev.sh (to start development servers)"
echo ""
echo "📖 For detailed instructions, see: OAUTH_SETUP.md"
